# Força a ativação do perfil 'dev' para desenvolvimento local.
# O Spring vai carregar este arquivo, ver a linha abaixo, e em seguida carregar o application-dev.properties.
spring.profiles.active=dev

# --- CONFIGURAÇÕES DE PRODUÇÃO (ignoradas quando o perfil 'dev' está ativo) ---
# spring.datasource.url=${DB_URL}
# spring.flyway.url=${DB_URL}
# spring.jpa.hibernate.ddl-auto=none
