# Ativa o perfil 'dev' por padrão.
# O Spring vai carregar este arquivo, ver a linha abaixo, e em seguida carregar o application-dev.properties
# spring.profiles.active=dev

# As configurações de produção que usam ${DB_URL} não serão mais usadas localmente.
spring.datasource.url=${DB_URL}
spring.flyway.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=none
